name: dart_docs_alfred_workflow
description: Search the Dart documentation using Alfred

version: 1.1.0

publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  algoliasearch: ^1.7.0
  args: ^2.5.0
  alfred_workflow: ^0.6.1
  cli_script: ^1.0.0
  envied: ^0.5.4+1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  json_serializable: ^6.8.0
  lints: ^3.0.0
