name: dart_docs_alfred_workflow
description: Search the Dart documentation using Alfred

version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  algolia: ^1.0.4
  args: ^2.3.0
  alfred_workflow: ^0.1.3

dev_dependencies:
  lints: ^1.0.0
  dart_code_metrics: ^4.8.1
